name: OWASP Dependency Check

on:
  push:
    branches: ["main"]

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node dependencies
        working-directory: gruppe-4a-1/webserver
        run: npm install

      - name: Install PHP dependencies (Laravel)
        working-directory: gruppe-4a-1/webserver
        run: composer install --no-interaction --no-progress
        
      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'gruppe-4a-1'
          path: './gruppe-4a-1/webserver'
          format: 'HTML'
          out: 'reports'
          args: >
              --enableRetireJS
              --enableExperimental
              --prettyPrint
              --noupdate
              --exclude **/vendor/**
              --exclude **/node_modules/**

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports
